name = "Lean2055"
defaultTargets = ["MyWork"]
reservoir = false

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.19.0"

[[lean_lib]]
name = "Lean2055"

[[lean_lib]]
name = "MyWork"
globs = ["MyWork.+"]
